name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
      -uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '7.5.5'
          projectPath: '$'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey= $ --config -webui.autoUpdateDrivers=true'