name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: "Install global packages"
        run: npm install -g yarn prisma-cli concurrently mocha
      - name: "Install build start test deps"
        env: 
          CI: false
        run: |
          yarn install &
          yarn run build
      
      - name: "Start test deps"
        env: 
          CI: false
        run: |
          yarn start &
          yarn test
      - name: Katalon Github Action
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '7.5.5'
          projectPath: '$'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey= $ --config -webui.autoUpdateDrivers=true'