name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
    - name: "Install global packages"
      run: npm install -g yarn prisma-cli concurrently mocha
    - name: "Run docker Container"
      run: docker-compose -f docker-compose.yml up --build -d
    - name: "Install deps"
      run: yarn install
    - name: "Build app"
      run: yarn build
    - name: "Start backend and frontend concurrently on background and run tests"
      run: |
        yarn start &
        sleep 10 &&
        curl http://localhost:3000 &&
        yarn test
    - name: Katalon Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '7.5.5'
          projectPath: '$'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey= $ --config -webui.autoUpdateDrivers=true'